


<script setup lang="ts">
  import Card from "../components/Card.vue";
  import { ref } from 'vue'

    //const pages : Page[] = getPages();
    const cards = ref([
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    },
    {
      src:"src/assets/0449_DETAIL_MENUISERIE_CUISINES_31.jpg",
      filename:"filename",
      affaire:"affaire",
      echelle:1
    }
  ])


  </script>
<template>
  <div class="cards">
    <Card v-for="(page,i) in cards" v-bind="page"></Card>
  </div>
</template>
 
<style scoped>

.cards {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  grid-auto-rows: var(10px);
  grid-gap: 2rem;
  right: 0;
  left: 0;
  padding-bottom: 200px;
}

</style>
